// TS+Vue3/chitu-project/src/components/Father.vue
<template>
    <h1>父组件</h1>
    <Child name="张三" :age="20" :gender="gender" @getChildData="getChildData"></Child>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Child from './Child.vue'

const gender = ref('男');
const getChildData = (data: string) => {
    console.log('子组件传递数据', data);

}
</script>

<style scoped></style>

// react/react-demo/src/components/09-组件传值/Father.jsx
import React, { Component } from 'react'
import Child from './Child';

export default class Father extends Component {
    getChildData = (data) => {
        console.log('输出子传父的参数', data);
    }

    render() {
        return (
            <div>
                <Child name='张三' age={20} getChildData={this.getChildData}></Child>
                {/* <Child age={30}></Child> */}
            </div>
        )
    }
}
